### ISSUE TITLE
Poprawa poruszania się po wyznaczonej ścieżce

### ISSUE THREAD

**Issue by KacperObara** [Sweaty-Bacon-Ducks/DigThemGraves#18]
Obecnie postać gracza bardzo łatwo się blokuje na przeszkodach.

**Comment by copy-on-meow** [comment]
Naprawione w a3a80ee5c829cdf78b3fb33d29b32c8bdcef531d 
Generalnie trzeba zmienić sposób poruszania się na taki który przykleja postać do krawędzi grafu, wtedy nie ma problemu z blokowaniem się na przeszkodach.
Ale myślę że to dość specyficzny problem dla naszego testowego levelu i trzeba będzie zrobić fine-tunning już w naszych produkcyjnych levelach
